EVG-6595: Get all patches for a project
evergreen-ci/evergreen.js pull request #12
Opened 2019-11-20 16:00 UTC by SupaJoon

https://jira.mongodb.org/browse/EVG-6595

Get all of the patches for a project by calling getProjectPatches with the project name

2019-11-20 18:06 UTC, tgrander requested changes

2019-11-20 18:06 UTC, tgrander commented on src/evergreen.ts
> +    const resource = "json/patches/project/" + projectName
nit: prefer the use of template literals over string concatenation, i.e. `json/patches/project/${projectName}`

2019-11-20 18:10 UTC, tgrander requested changes

2019-11-20 18:10 UTC, tgrander commented on src/evergreen.ts
> +      page: page,
don't have to include the value since the key and value are the same

2019-11-20 20:45 UTC, john-m-liu approved these changes
Looks good but be sure to increment the version number before merging (we'll also need to publish to npm, but we can do that later)

2019-11-20 21:24 UTC, tgrander approved these changes

2019-11-21 16:41 UTC, john-m-liu commented
There's a mismatch between our linter and the default prettier settings, where one is checking for a trailing comma in the last field of a JSON object and the other isn't. Which way do we want to go with this? I personally like having the trailing comma since it makes adding new fields easier

2019-11-21 16:59 UTC, tgrander commented
@john-m-liu i also like trailing comma

2019-11-21 17:03 UTC, john-m-liu commented
Arjun if you agree, then let's add a prettier section in our package.json file with `trailingComma` set to `es5`

2019-11-21 18:36 UTC, merged